/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.processmining.scala.viewers.spectrum.view;

import org.deckfour.xes.model.XLog;

import javax.swing.*;
import java.awt.*;

/**
 * @author nlvden
 */
public class PreProcessingDialog extends javax.swing.JDialog {

    private final Frame parent;
    private final boolean useDuration;
    /**
     * Creates new form PreProcessingDialog
     */
    public PreProcessingDialog(final Frame parent, final String filename, final boolean useDuration) {
        super(parent, true);
        this.parent = parent;
        this.useDuration = useDuration;
        initComponents(null);
        preProcessingPanel1.jTextFieldFileName.setText(filename);
        centerWindow(this);
    }

    public PreProcessingDialog(final Frame parent, final XLog xlog) {
        super(parent, true);
        this.parent = parent;
        this.useDuration = true;
        initComponents(xlog);
        centerWindow(this);

    }

    private String dir = "";

    public String getDir() {
        return dir;
    }

    private void consumer(final String dir) {
        this.dir = dir;
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        dispose();
    }

    static void centerWindow(final Window frame) {
        final Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        final int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        final int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        frame.setLocation(x, y);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(final XLog xlog) {
        preProcessingPanel1 = new PreProcessingPanel(parent, xlog, (dir) -> consumer(dir), useDuration);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Event Log Pre-Processing");
        setMinimumSize(new java.awt.Dimension(700, 400));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(preProcessingPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(preProcessingPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.processmining.scala.viewers.spectrum.view.PreProcessingPanel preProcessingPanel1;
    // End of variables declaration//GEN-END:variables
}
